final Map<String, List<String>> _districts = {
  'Hà Nội': [
    'Quận Ba Đình',
    'Quận Hoàn Kiếm',
    'Quận Hai Bà Trưng',
    'Quận Đống Đa',
    'Quận Cầu Giấy',
    'Quận Tây Hồ',
    'Quận Thanh Xuân',
    'Quận Hoàng Mai',
    'Quận Long Biên',
    'Quận Bắc Từ Liêm',
    'Quận Nam Từ Liêm',
    'Huyện Thanh Trì',
    'Huyện Gia Lâm',
    'Huyện Đông Anh',
    'Huyện Sóc Sơn',
    'Huyện Hoài Đức',
    'Huyện Quốc Oai',
    'Huyện Thanh Oai',
    'Huyện Thường Tín',
    'Huyện Phú Xuyên',
    'Huyện Ba Vì',
    'Huyện Phúc Thọ',
    'Huyện Chương Mỹ',
    'Huyện Đan Phượng',
    'Huyện Mỹ Đức',
    'Huyện Thạch Thất',
    'Huyện Ứng Hòa',
    'Thị xã Sơn Tây'
  ],
  'Hồ Chí Minh': [
    'Quận 1',
    'Quận 3',
    'Quận 4',
    'Quận 5',
    'Quận 6',
    'Quận 7',
    'Quận 8',
    'Quận 10',
    'Quận 11',
    'Quận 12',
    'Quận Bình Thạnh',
    'Quận Tân Bình',
    'Quận Tân Phú',
    'Quận Phú Nhuận',
    'Quận Gò Vấp',
    'Quận Bình Tân',
    'Quận Thủ Đức',
    'Huyện Nhà Bè',
    'Huyện Hóc Môn',
    'Huyện Củ Chi',
    'Huyện Bình Chánh',
    'Huyện Cần Giờ'
  ],
  'Đà Nẵng': [
    'Quận Hải Châu',
    'Quận Thanh Khê',
    'Quận Sơn Trà',
    'Quận Ngũ Hành Sơn',
    'Quận Liên Chiểu',
    'Quận Cẩm Lệ',
    'Huyện Hòa Vang',
    'Huyện Hoàng Sa'
  ],
  'Hải Phòng': [
    'Quận Hồng Bàng',
    'Quận Lê Chân',
    'Quận Ngô Quyền',
    'Quận Kiến An',
    'Quận Hải An',
    'Quận Đồ Sơn',
    'Quận Dương Kinh',
    'Huyện An Dương',
    'Huyện An Lão',
    'Huyện Kiến Thụy',
    'Huyện Tiên Lãng',
    'Huyện Vĩnh Bảo',
    'Huyện Thủy Nguyên',
    'Huyện Cát Hải',
    'Huyện Bạch Long Vĩ'
  ],
  'Cần Thơ': [
    'Quận Ninh Kiều',
    'Quận Bình Thủy',
    'Quận Cái Răng',
    'Quận Ô Môn',
    'Quận Thốt Nốt',
    'Huyện Phong Điền',
    'Huyện Thới Lai',
    'Huyện Cờ Đỏ',
    'Huyện Vĩnh Thạnh'
  ],
  'Bà Rịa - Vũng Tàu': [
    'Thành phố Vũng Tàu',
    'Thành phố Bà Rịa',
    'Huyện Châu Đức',
    'Huyện Đất Đỏ',
    'Huyện Long Điền',
    'Huyện Tân Thành',
    'Huyện Xuyên Mộc',
    'Huyện Côn Đảo'
  ],
};
